apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongo-app-chart.fullname" . }}-db-secret
  labels:
  {{- include "mongo-app-chart.labels" . | nindent 4 }}
data:
  mongo-root-password: {{ required "dbSecret.mongoRootPassword is required" .Values.dbSecret.mongoRootPassword
    | quote }}
  mongo-root-username: {{ required "dbSecret.mongoRootUsername is required" .Values.dbSecret.mongoRootUsername
    | quote }}
type: Opaque