apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mongo-app-chart.fullname" . }}-db-configmap
  labels:
  {{- include "mongo-app-chart.labels" . | nindent 4 }}
data:
  database_url: {{ printf "%s-%s" (include "mongo-app-chart.fullname" .) .Values.dbConfigmap.databaseUrl | quote }}