dbConfigmap:
  databaseUrl: mongodb-service
dbDeployment:
  mongodb:
    image:
      repository: docker.io/library/mongo
      tag: latest
  replicas: 1
dbSecret:
  mongoRootPassword: ""
  mongoRootUsername: ""
dbService:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  type: ClusterIP
express:
  mongoExpress:
    image:
      repository: docker.io/community/mongo-express
      tag: latest
  replicas: 1
expressService:
  ports:
  - nodePort: 30000
    port: 8081
    protocol: TCP
    targetPort: 8081
  type: LoadBalancer
kubernetesClusterDomain: cluster.local
