dbConfigmap:
  databaseUrl: db-service
dbDeployment:
  mongodb:
    image:
      repository: docker.io/library/mongo
      tag: latest
  replicas: 1
dbSecret:
  mongoRootPassword: "dXNlcm5hbWU="
  mongoRootUsername: "cGFzc3dvcmQ="
dbService:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  type: ClusterIP
express:
  mongoExpress:
    image:
      repository: docker.io/mongo-express
      tag: latest
  replicas: 1
expressService:
  ports:
  - nodePort: 0 #30000
    port: 8081
    protocol: TCP
    targetPort: 8081
  type: LoadBalancer
kubernetesClusterDomain: cluster.local
